services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - itdesk-network
  itdesk-api:
    restart: always
    build:
      context: .
      dockerfile: ./ITDeskServer/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5005:8080"
      - "5006:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ITDesk;User=sa;Password=${MSSQL_SA_PASSWORD}
    networks:
      - itdesk-network
  itdesk-client:
    restart: always
    build:
      context: .
      dockerfile: ./ITDeskClient/Dockerfile
    ports:
      - "5009:80"
    networks:
      - itdesk-network
networks:
  itdesk-network:
    driver: bridge
