services:
  postgres:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      POSTGRES_DB: itdesk
      POSTGRES_USER: itdesksa
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - itdesk-network
  itdesk-api:
    restart: always
    build:
      context: .
      dockerfile: ./ITDeskServer/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5005:8080"
      - "5006:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=itdesk;Username=itdesksa;Password=${POSTGRES_PASSWORD}
    networks:
      - itdesk-network
  itdesk-client:
    restart: always
    build:
      context: .
      dockerfile: ./ITDeskClient/Dockerfile
    ports:
      - "5009:80"
    networks:
      - itdesk-network
networks:
  itdesk-network:
    driver: bridge

volumes:
  postgres_data: